[versions]
microcks-testcontainers = "0.5.0"
testcontainers = "2.0.5"
kafka = "3.9.1"
junit-jupiter = "5.13.4"
junit-platform = "1.13.4"
slf4j = "2.0.17"

[libraries]
microcks-testcontainers = { module = "io.github.microcks:microcks-testcontainers", version.ref = "microcks-testcontainers" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-kafka = { module = "org.testcontainers:testcontainers-kafka", version.ref = "testcontainers" }
kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
