package com.arc_e_tect.gradle.apionly.transcriberj.restdocs;

import com.arc_e_tect.gradle.apionly.transcriberj.model.Operation;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.CaseKind;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.ContractCase;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.EmitterContext;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.GeneratedClass;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * The contract tests: per operation with cases, an interface of one test per case, of every kind
 * the core derives; one support class they share; and the exception a fixture hook that is not
 * implemented yet throws.
 */
final class ContractTests {

    /** The emitter option that switches rendering on. */
    static final String OPTION = "tests";

    /** The shared support class. */
    static final String SUPPORT = "ContractTestSupport";

    /** The exception the state hook throws until it is implemented. */
    static final String EXCEPTION = "FixtureNotImplementedException";

    /** What an interface's name ends with, after the operation's stem. */
    static final String SUFFIX = "ContractTests";

    /** What the core's case class names end with. */
    private static final String CORE_SUFFIX = "ContractCases";

    /** The snippet directory every test documents under, unless a test overrides it. */
    static final String PREFIX = "generated";

    /**
     * The paragraph that closes the Javadoc of every interface and of the support class: the
     * snippets the tests write are how the response is validated, not documentation.
     */
    static final String NOT_DOCUMENTATION = """
             *
             * <p>The snippets these tests write are a by-product of validation: {@code document()} is where
             * Spring REST Docs checks a response against its declared fields. They are not documentation,
             * and are not meant to be published.
            """;

    private static final String INDENT = "    ";
    private static final String EXCLUDE_FROM_COVERAGE = "@com.arc_e_tect.sedr.utils.jacoco.marker"
            + ".ExcludeFromJacocoGeneratedCodeCoverage(justification = \"Generated by API-Only TranscriberJ\")\n";
    private static final char QUOTE = 34;
    private static final char BACKSLASH = 92;
    private static final Set<String> KEYWORDS = Set.of(
            "abstract", "assert", "boolean", "break", "byte", "case", "catch", "char", "class", "const",
            "continue", "default", "do", "double", "else", "enum", "extends", "final", "finally", "float",
            "for", "goto", "if", "implements", "import", "instanceof", "int", "interface", "long", "native",
            "new", "package", "private", "protected", "public", "return", "short", "static", "strictfp",
            "super", "switch", "synchronized", "this", "throw", "throws", "transient", "try", "void",
            "volatile", "while", "true", "false", "null", "var", "record", "yield", "sealed", "permits");

    /** The WebTestClient methods that start a request of a method, without naming it. */
    private static final Set<String> VERBS = Set.of("GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "OPTIONS");

    /** The verbs whose WebTestClient spec takes a body. */
    private static final Set<String> BODY_VERBS = Set.of("POST", "PUT", "PATCH");

    private static final Pattern PLACEHOLDER = Pattern.compile("\\{([^}]+)}");

    /**
     * What a target's fixture must do before a case that requires state, per kind: the table the
     * core's {@code ContractCase} carries, in every interface with such a case.
     */
    static final String STATE_TABLE = """
            * <table>
            *   <caption>What {@code arrangeState} must do, per kind</caption>
            *   <tr><th>Kind</th><th>Real implementation</th><th>Double</th></tr>
            *   <tr><td>{@code SUCCESS}</td><td>Put the service in the state that makes the case's status the
            *   right answer: the resource exists for a read, an update or a delete, and does not exist for a
            *   create.</td><td>Serve the case's response.</td></tr>
            *   <tr><td>{@code NOT_FOUND}</td><td>Make sure the resource the path names does not
            *   exist.</td><td>Serve the case's response.</td></tr>
            * </table>
            """;

    private ContractTests() {
    }

    /**
     * Whether the project switched rendering on. Only {@value #OPTION} is an option; any other
     * name is a mistake, and fails generation rather than being ignored.
     */
    static boolean enabled(Map<String, String> options) {
        for (String name : options.keySet()) {
            if (!name.equals(OPTION)) {
                throw new IllegalArgumentException("The REST Docs emitter has no option '" + name
                        + "'; its only option is '" + OPTION + "'.");
            }
        }
        return "true".equalsIgnoreCase(options.getOrDefault(OPTION, "false").trim());
    }

    /** Writes every interface, and the support class and the exception when there is one. */
    static void emit(EmitterContext context, String header, String pkg, String base) {
        boolean any = false;
        for (Operation operation : context.model().operations()) {
            String location = location(operation);
            List<ContractCase> cases = context.contractCases(location);
            if (cases.isEmpty()) continue;
            GeneratedClass casesClass = context.names().contractCases(location).orElseThrow();
            GeneratedClass operationClass = context.names().operation(location).orElseThrow();
            String stem = casesClass.simpleName().endsWith(CORE_SUFFIX)
                    ? casesClass.simpleName().substring(0, casesClass.simpleName().length() - CORE_SUFFIX.length())
                    : casesClass.simpleName();
            Rendered r = new Rendered(stem + SUFFIX, operation, operationClass.simpleName(),
                    casesClass.simpleName(), cases, documented(context));
            context.writeJava(pkg, r.name(), r.source(header, pkg, base));
            any = true;
        }
        if (any) {
            context.writeJava(pkg, SUPPORT, support(header, pkg, base));
            context.writeJava(pkg, EXCEPTION, exception(header, pkg, base));
        }
    }

    /** The operation's JSON pointer, as the core keys it. */
    private static String location(Operation operation) {
        return "/paths/" + operation.path().replace("~", "~0").replace("/", "~1") + "/" + operation.method().key();
    }

    /** The simple names of the classes that have a REST Docs companion. */
    private static Set<String> documented(EmitterContext context) {
        Set<String> out = new HashSet<>();
        for (GeneratedClass generated : context.names().all()) {
            if (generated.exposed() && generated.bodyShaped()) out.add(generated.simpleName());
        }
        return out;
    }

    /**
     * The state a case needs, as a sentence a comment can hold: for a not-found case, that the
     * resource its path names does not exist; for a success case expecting {@code 201}, that what
     * it creates does not exist yet; for any other success case, that the resource exists, or,
     * without a path parameter to name one, that the service answers the case's status.
     */
    static String state(ContractCase c, String path) {
        List<String> names = new ArrayList<>();
        Matcher m = PLACEHOLDER.matcher(path);
        while (m.find()) names.add(m.group(1));
        List<String> values = c.request().pathParameters();
        String resource = null;
        if (!names.isEmpty()) {
            List<String> pairs = new ArrayList<>();
            for (int i = 0; i < names.size() && i < values.size(); i++) {
                pairs.add(names.get(i) + " = " + literal(values.get(i)));
            }
            resource = "the resource at " + path + " with " + String.join(", ", pairs);
        }
        String verb = c.request().method().toUpperCase(Locale.ROOT);
        if (c.kind() == CaseKind.NOT_FOUND) {
            return "make sure " + (resource == null ? "what " + verb + " " + path + " reads" : resource)
                    + " does not exist";
        }
        if (c.expectedStatus() == 201) {
            return "make sure " + (resource == null ? "what " + verb + " " + path + " creates" : resource)
                    + " does not exist yet";
        }
        return resource == null
                ? "make sure the service is in the state in which " + verb + " " + path + " answers "
                + c.expectedStatus()
                : "make sure " + resource + " exists";
    }

    /**
     * The suggested implementation of {@code arrangeState} for an operation's cases, line by line:
     * a switch over the ids of the cases that require state, each with a comment saying the state
     * it needs, and a default that fails for any other.
     */
    static List<String> suggestion(List<ContractCase> cases, String path) {
        List<String> out = new ArrayList<>();
        out.add("@Override");
        out.add("public void arrangeState(ContractCase contractCase) {");
        out.add(INDENT + "switch (contractCase.id()) {");
        for (ContractCase c : cases) {
            if (!c.requiresState()) continue;
            out.add(INDENT + INDENT + "case " + literal(c.id()) + " -> {");
            out.add(INDENT + INDENT + INDENT + "// " + state(c, path));
            out.add(INDENT + INDENT + "}");
        }
        out.add(INDENT + INDENT + "default -> throw new IllegalArgumentException(\"No state to arrange for case \" "
                + "+ contractCase.id());");
        out.add(INDENT + "}");
        out.add("}");
        return out;
    }

    /** One interface. */
    private record Rendered(String name, Operation operation, String operationClass, String casesClass,
                            List<ContractCase> cases, Set<String> documented) {

        boolean stateful() {
            return cases.stream().anyMatch(ContractCase::requiresState);
        }

        String source(String header, String pkg, String base) {
            StringBuilder out = new StringBuilder(header);
            out.append("package ").append(pkg).append(";\n\n")
                    .append("import ").append(base).append(".ContractCase;\n")
                    .append("import ").append(base).append('.').append(casesClass).append(";\n")
                    .append("import ").append(base).append('.').append(operationClass).append(";\n")
                    .append("import org.junit.jupiter.api.DisplayName;\n")
                    .append("import org.junit.jupiter.api.Test;\n")
                    .append("import org.springframework.test.web.reactive.server.WebTestClient;\n\n")
                    .append("import static org.springframework.restdocs.webtestclient.WebTestClientRestDocumentation"
                            + ".document;\n\n");
            out.append("/**\n")
                    .append(" * Contract tests of operation ").append(comment(operation.method().name())).append(' ')
                    .append(comment(operation.path())).append(": one per case in {@link ").append(casesClass)
                    .append("},\n")
                    .append(" * each sending the case's request exactly and expecting the response the contract\n")
                    .append(" * declares for it.\n")
                    .append(" *\n")
                    .append(" * <p>The tests are the same whichever implementation {@link #client()} is bound to: the\n")
                    .append(" * real one, or a double. Only the fixture hooks differ: ");
            if (stateful()) {
                out.append("{@link #arrangeState(ContractCase)} before\n")
                        .append(" * a case that requires state, and {@link #arrangeStatelessCase(ContractCase)} before\n")
                        .append(" * one that does not.\n");
            } else {
                out.append("{@link #arrangeStatelessCase(ContractCase)}, before\n")
                        .append(" * every case, as none requires state.\n");
            }
            out.append(NOT_DOCUMENTATION)
                    .append(" */\n")
                    .append(EXCLUDE_FROM_COVERAGE)
                    .append("public interface ").append(name).append(" {\n\n");
            out.append(INDENT).append("/**\n")
                    .append(INDENT).append(" * The client the requests are sent with, bound to the implementation under test and\n")
                    .append(INDENT).append(" * configured for Spring REST Docs.\n")
                    .append(INDENT).append(" *\n")
                    .append(INDENT).append(" * @return the client\n")
                    .append(INDENT).append(" */\n")
                    .append(INDENT).append("WebTestClient client();\n\n");
            if (stateful()) arrangeState(out);
            out.append(INDENT).append("/**\n")
                    .append(INDENT).append(" * Prepares the implementation under test for one case that needs no state -- not\n")
                    .append(INDENT).append(" * acceptable, unsupported media type or invalid request -- just before it is sent.\n")
                    .append(INDENT).append(" *\n")
                    .append(INDENT).append(" * <p>Empty, because the real implementation needs nothing: it refuses such a request\n")
                    .append(INDENT).append(" * before any state is consulted -- its inbound adapter rejects a contract violation\n")
                    .append(INDENT).append(" * before the port is called -- so none needs arranging. A double, such as a WireMock\n")
                    .append(INDENT).append(" * stub, overrides it to answer the request as the contract declares.\n")
                    .append(INDENT).append(" *\n")
                    .append(INDENT).append(" * <p><b>WARNING:</b> these tests are only as independent as the implementation is\n")
                    .append(INDENT).append(" * correct. A request the implementation wrongly accepts may leave state behind -- a\n")
                    .append(INDENT).append(" * resource created from an invalid body -- that the tests after it then see. The\n")
                    .append(INDENT).append(" * failing test reports that defect; until it is fixed, reset the state between runs.\n")
                    .append(INDENT).append(" *\n")
                    .append(INDENT).append(" * @param contractCase the case about to be sent\n")
                    .append(INDENT).append(" */\n")
                    .append(INDENT).append("default void arrangeStatelessCase(ContractCase contractCase) {\n")
                    .append(INDENT).append("}\n\n");
            out.append(INDENT).append("/**\n")
                    .append(INDENT).append(" * The directory, under the snippets directory, every test documents in:\n")
                    .append(INDENT).append(" * {@code <prefix>/<operationId>/<caseId>}. Overridden by a variant whose snippets must\n")
                    .append(INDENT).append(" * not overwrite another's.\n")
                    .append(INDENT).append(" *\n")
                    .append(INDENT).append(" * @return the prefix; {@value ").append(SUPPORT)
                    .append("#DEFAULT_PREFIX} unless overridden\n")
                    .append(INDENT).append(" */\n")
                    .append(INDENT).append("default String generatedDocumentationPrefix() {\n")
                    .append(INDENT).append(INDENT).append("return ").append(SUPPORT).append(".DEFAULT_PREFIX;\n")
                    .append(INDENT).append("}\n");
            Set<String> methods = new HashSet<>();
            for (ContractCase c : cases) {
                String method = variableName(c.id()) + "_returns" + c.expectedStatus();
                if (!methods.add(method)) {
                    method = method + "_" + c.index();
                    methods.add(method);
                }
                test(out, c, method);
            }
            return out.append("}\n").toString();
        }

        /** The state hook, which throws until it is implemented, with its suggested implementation. */
        private void arrangeState(StringBuilder out) {
            List<String> suggestion = suggestion(cases, operation.path());
            out.append(INDENT).append("/**\n")
                    .append(INDENT).append(" * Puts the implementation under test in the state one case needs, just before its\n")
                    .append(INDENT).append(" * request is sent: called before every success and not-found case, whose\n")
                    .append(INDENT).append(" * {@code requiresState} is true.\n")
                    .append(INDENT).append(" *\n");
            for (String line : STATE_TABLE.lines().toList()) out.append(INDENT).append(' ').append(line).append('\n');
            out.append(INDENT).append(" *\n")
                    .append(INDENT).append(" * <p>Switch on the case's id -- or on its kind, status and variant -- and arrange\n")
                    .append(INDENT).append(" * exactly that. If the service then answers otherwise than the case expects, that is\n")
                    .append(INDENT).append(" * a defect in the service, not in the test. A correct implementation of this hook is\n")
                    .append(INDENT).append(" * what makes these tests independent and repeatable, in any order, any number of times.\n")
                    .append(INDENT).append(" *\n")
                    .append(INDENT).append(" * <p>Until it is implemented, it throws {@link ").append(EXCEPTION)
                    .append("}, and every test that needs\n")
                    .append(INDENT).append(" * state fails, saying which state it is waiting for. An implementation starts as:\n")
                    .append(INDENT).append(" *\n")
                    .append(INDENT).append(" * <pre>\n");
            for (String line : suggestion) out.append(INDENT).append(" * ").append(comment(line)).append('\n');
            out.append(INDENT).append(" * </pre>\n")
                    .append(INDENT).append(" *\n")
                    .append(INDENT).append(" * @param contractCase the case about to be sent\n")
                    .append(INDENT).append(" */\n")
                    .append(INDENT).append("default void arrangeState(ContractCase contractCase) {\n")
                    .append(INDENT).append(INDENT).append("throw new ").append(EXCEPTION).append("(contractCase, ")
                    .append(literal(name)).append(", ").append(literal(String.join("\n", suggestion)))
                    .append(");\n")
                    .append(INDENT).append("}\n\n");
        }

        private void test(StringBuilder out, ContractCase c, String method) {
            String verb = c.request().method().toUpperCase(Locale.ROOT);
            boolean body = c.request().body() != null;
            String display = verb + " " + operation.path() + ": " + c.description() + " returns "
                    + c.expectedStatus();
            String i2 = INDENT + INDENT;
            String i4 = i2 + i2;
            out.append('\n')
                    .append(INDENT).append("/** ").append(comment(c.description())).append(". */\n")
                    .append(INDENT).append("@Test\n")
                    .append(INDENT).append("@DisplayName(").append(literal(display)).append(")\n")
                    .append(INDENT).append("default void ").append(method).append("() {\n")
                    .append(i2).append("ContractCase contractCase = ").append(casesClass).append(".CASES.get(")
                    .append(c.index()).append(");\n")
                    .append(i2).append(c.requiresState() ? "arrangeState" : "arrangeStatelessCase")
                    .append("(contractCase);\n")
                    .append(i2).append(SUPPORT).append(".clientFor(client(), contractCase)");
            if (VERBS.contains(verb) && (!body || BODY_VERBS.contains(verb))) {
                out.append('.').append(verb.toLowerCase(Locale.ROOT)).append("()\n");
            } else {
                out.append(".method(org.springframework.http.HttpMethod.valueOf(contractCase.request().method()))\n");
            }
            out.append(i4).append(".uri(").append(operationClass).append(".PATH, ").append(SUPPORT)
                    .append(".pathValues(contractCase))\n");
            if (!c.request().headers().isEmpty()) {
                out.append(i4).append(".headers(headers -> ").append(SUPPORT)
                        .append(".headers(headers, contractCase))\n");
            }
            if (body) {
                out.append(i4).append(".contentType(").append(SUPPORT).append(".contentType(contractCase))\n")
                        .append(i4).append(".bodyValue(").append(SUPPORT).append(".body(contractCase))\n");
            }
            out.append(i4).append(".exchange()\n")
                    .append(i4).append(".expectBody()\n")
                    .append(i4).append(".consumeWith(result -> ").append(SUPPORT)
                    .append(".assertStatus(contractCase, result.getStatus().value()))\n");
            if (!c.expectedContentTypes().isEmpty()) {
                out.append(i4).append(".consumeWith(result -> ").append(SUPPORT)
                        .append(".assertContentType(contractCase,\n")
                        .append(i4).append(INDENT + INDENT)
                        .append("result.getResponseHeaders().get(org.springframework.http.HttpHeaders.CONTENT_TYPE)))\n");
            }
            out.append(i4).append(".consumeWith(document(").append(SUPPORT)
                    .append(".identifier(generatedDocumentationPrefix(),\n")
                    .append(i4).append(INDENT + INDENT + INDENT + INDENT)
                    .append(operation.operationId() != null ? operationClass + ".OPERATION_ID"
                            : SUPPORT + ".operationName(" + operationClass + ".class)")
                    .append(", contractCase)");
            if (c.responseBodyClass() != null && documented.contains(c.responseBodyClass())) {
                out.append(",\n").append(i4).append(INDENT + INDENT).append(c.responseBodyClass())
                        .append("Docs.responseFields()");
            }
            out.append("));\n").append(INDENT).append("}\n");
        }
    }

    /** The exception the state hook throws until it is implemented. */
    static String exception(String header, String pkg, String base) {
        return header + """
                package %1$s;

                import %2$s.ContractCase;

                /**
                 * Thrown by a contract test's {@code arrangeState} until the class implementing the interface
                 * overrides it: the test needs the implementation under test in a particular state, and nothing
                 * has put it there yet. Like a Cucumber step without a definition, the project compiles and runs,
                 * and each test that needs state fails, saying which state it is waiting for.
                 *
                 * <p>Its message names the case -- operation, id, kind, status, variant and path values -- and
                 * ends with a suggested implementation of {@code arrangeState} for the case's operation, to paste
                 * into that class and complete.
                 */
                @com.arc_e_tect.sedr.utils.jacoco.marker.ExcludeFromJacocoGeneratedCodeCoverage(justification = "Generated by API-Only TranscriberJ")
                public class FixtureNotImplementedException extends org.opentest4j.AssertionFailedError {

                    private static final long serialVersionUID = 1L;

                    /**
                     * The failure of one case whose state is not arranged.
                     *
                     * @param contractCase  the case
                     * @param testInterface the simple name of the interface whose {@code arrangeState} is not
                     *                      implemented
                     * @param suggestion    a suggested implementation of it
                     */
                    public FixtureNotImplementedException(ContractCase contractCase, String testInterface,
                                                          String suggestion) {
                        super(message(contractCase, testInterface, suggestion));
                    }

                    /**
                     * The message: the case, the state it needs, and the suggested implementation.
                     *
                     * @param contractCase  the case
                     * @param testInterface the interface
                     * @param suggestion    the suggested implementation
                     * @return the message
                     */
                    static String message(ContractCase contractCase, String testInterface, String suggestion) {
                        String variant = contractCase.variant() == null ? "" : ", variant " + contractCase.variant();
                        return "Case " + contractCase.id() + " of " + contractCase.request().method() + " "
                                + contractCase.request().pathTemplate() + " (" + contractCase.kind() + ", expects "
                                + contractCase.expectedStatus() + variant + ", path values "
                                + contractCase.request().pathParameters() + ") needs the implementation under test in a "
                                + "particular state, but arrangeState is not implemented yet.\\n"
                                + (contractCase.kind().name().equals("NOT_FOUND")
                                ? "Make sure the resource the path names does not exist."
                                : "Put the service in the state that makes " + contractCase.expectedStatus()
                                + " the right answer: the resource exists for a read, an update or a delete, and does "
                                + "not exist for a create.")
                                + "\\nImplement arrangeState in the class that implements " + testInterface
                                + ". It starts as:\\n\\n" + suggestion + "\\n";
                    }
                }
                """.formatted(pkg, base);
    }

    /** The class every interface's tests share. */
    static String support(String header, String pkg, String base) {
        return header + """
                package %1$s;

                import %2$s.ContractCase;
                import org.springframework.http.HttpHeaders;
                import org.springframework.http.MediaType;
                import org.springframework.web.reactive.function.client.ClientRequest;
                import org.springframework.test.web.reactive.server.WebTestClient;

                import java.net.URI;
                import java.nio.charset.StandardCharsets;
                import java.util.List;
                import java.util.stream.Collectors;

                /**
                 * What the generated contract tests share: sending a case's request exactly, and saying, when
                 * the response is not the one the contract declares, where to look.
                %4$s */
                @com.arc_e_tect.sedr.utils.jacoco.marker.ExcludeFromJacocoGeneratedCodeCoverage(justification = "Generated by API-Only TranscriberJ")
                public final class ContractTestSupport {

                    /** The directory, under the snippets directory, the tests document in by default. */
                    public static final String DEFAULT_PREFIX = "%3$s";

                    private static final String UNRESERVED =
                            "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~";

                    private ContractTestSupport() {
                    }

                    /**
                     * The client to send a case's request with: the one given, or, where the request has query
                     * parameters, one that adds them to the URI exactly, since the operation's {@code PATH} is
                     * the whole URI template.
                     *
                     * @param client  the client under test
                     * @param contractCase the case
                     * @return the client to send it with
                     */
                    public static WebTestClient clientFor(WebTestClient client, ContractCase contractCase) {
                        if (contractCase.request().query().isEmpty()) return client;
                        String query = query(contractCase);
                        return client.mutate().filter((request, next) -> next.exchange(ClientRequest.from(request)
                                .url(withQuery(request.url(), query)).build())).build();
                    }

                    /**
                     * A URI with its query replaced.
                     *
                     * @param uri   the URI
                     * @param query the query, already encoded
                     * @return the URI with that query
                     */
                    static URI withQuery(URI uri, String query) {
                        return URI.create(uri.getScheme() + "://" + uri.getRawAuthority() + uri.getRawPath() + "?" + query);
                    }

                    /**
                     * A case's query parameters as a query string: every name and value percent-encoded as
                     * UTF-8, except the characters RFC 3986 leaves unreserved, so that a server decodes exactly
                     * the case's values -- {@code +} included.
                     *
                     * @param contractCase the case
                     * @return the query, without {@code ?}
                     */
                    public static String query(ContractCase contractCase) {
                        return contractCase.request().query().stream()
                                .map(p -> encode(p.name()) + "=" + encode(p.value()))
                                .collect(Collectors.joining("&"));
                    }

                    /**
                     * A value percent-encoded as UTF-8, except the characters RFC 3986 leaves unreserved.
                     *
                     * @param value the value
                     * @return the encoded value
                     */
                    static String encode(String value) {
                        StringBuilder out = new StringBuilder();
                        for (byte b : value.getBytes(StandardCharsets.UTF_8)) {
                            if (b >= 0 && UNRESERVED.indexOf(b) >= 0) {
                                out.append((char) b);
                            } else {
                                out.append('%%').append(String.format("%%02X", b & 0xff));
                            }
                        }
                        return out.toString();
                    }

                    /**
                     * The values that fill the operation's path template, in order; the client encodes them.
                     *
                     * @param contractCase the case
                     * @return the values
                     */
                    public static Object[] pathValues(ContractCase contractCase) {
                        return contractCase.request().pathParameters().toArray();
                    }

                    /**
                     * Adds a case's headers, exactly. A value that is not printable US-ASCII cannot be: HTTP
                     * header values are US-ASCII (RFC 9110), and HTTP clients replace or re-encode anything else,
                     * so the test fails before sending, rather than for a request the case does not describe.
                     *
                     * @param headers the request's headers
                     * @param contractCase the case
                     */
                    public static void headers(HttpHeaders headers, ContractCase contractCase) {
                        for (var header : contractCase.request().headers()) {
                            if (!header.value().chars().allMatch(c -> c >= 0x20 && c < 0x7f)) {
                                throw new AssertionError(subject(contractCase)
                                        + ": header " + header.name() + " holds '" + header.value() + "', which cannot "
                                        + "be sent as it is: HTTP header values are US-ASCII. Give the header's value in the "
                                        + "contract in US-ASCII.");
                            }
                            headers.add(header.name(), header.value());
                        }
                    }

                    /**
                     * A case's request content type.
                     *
                     * @param contractCase the case
                     * @return the content type
                     */
                    public static MediaType contentType(ContractCase contractCase) {
                        return MediaType.parseMediaType(contractCase.request().contentType());
                    }

                    /**
                     * A case's request body, exactly: its bytes, so that no encoder rewrites it.
                     *
                     * @param contractCase the case
                     * @return the body, as UTF-8
                     */
                    public static byte[] body(ContractCase contractCase) {
                        return contractCase.request().body().getBytes(StandardCharsets.UTF_8);
                    }

                    /**
                     * The name of an operation the contract gives no {@code operationId}: its class's simple
                     * name, without {@code Operation}.
                     *
                     * @param operationClass the operation's class
                     * @return the name
                     */
                    public static String operationName(Class<?> operationClass) {
                        String name = operationClass.getSimpleName();
                        return name.endsWith("Operation") ? name.substring(0, name.length() - "Operation".length()) : name;
                    }

                    /**
                     * Where a case's snippets are written: {@code <prefix>/<operationId>/<caseId>}.
                     *
                     * @param prefix      the prefix
                     * @param operationId the operation's id
                     * @param contractCase the case
                     * @return the REST Docs identifier
                     */
                    public static String identifier(String prefix, String operationId, ContractCase contractCase) {
                        return prefix + "/" + operationId + "/" + contractCase.id();
                    }

                    /**
                     * Fails, saying where to look, unless the status received is the one the case expects.
                     *
                     * @param contractCase the case
                     * @param received the status received
                     */
                    public static void assertStatus(ContractCase contractCase, int received) {
                        if (received != contractCase.expectedStatus()) {
                            throw new AssertionError(statusMessage(contractCase, received));
                        }
                    }

                    /**
                     * What a status other than the expected one says about the implementation, or its fixture:
                     * the case, and where to look.
                     *
                     * @param contractCase the case
                     * @param received     the status received
                     * @return the message
                     */
                    public static String statusMessage(ContractCase contractCase, int received) {
                        String subject = subject(contractCase) + ": expected " + contractCase.expectedStatus()
                                + ", received " + received + ".";
                        String cause = cause(contractCase, received);
                        return cause == null ? subject : subject + " " + cause;
                    }

                    /** How a message names a case: {@code <id> (<kind>: <description>[, at <where> <keyword>])}. */
                    static String subject(ContractCase contractCase) {
                        String at = contractCase.kind().name().equals("INVALID_REQUEST")
                                ? ", at " + where(contractCase) + " " + contractCase.keyword() : "";
                        return contractCase.id() + " (" + contractCase.kind() + ": " + contractCase.description() + at
                                + ")";
                    }

                    /** The probable cause of a status, by the case's kind; null when there is none to name. */
                    static String cause(ContractCase contractCase, int received) {
                        boolean success = received >= 200 && received < 300;
                        boolean failed = received >= 500 && received < 600;
                        String fixture = " Check arrangeState for this case.";
                        return switch (contractCase.kind().name()) {
                            case "SUCCESS" -> {
                                if (received == 400) {
                                    yield "The implementation rejects a request the contract declares valid. Compare its "
                                            + "validation with the contract: an anchored or stricter pattern, a stricter "
                                            + "length or bound, a member it requires that the contract makes optional, or an "
                                            + "optional member of the full request it does not know.";
                                } else if (received == 404) {
                                    yield "The fixture did not create the resource, or the implementation looks for it "
                                            + "somewhere else." + fixture;
                                } else if (received == 409) {
                                    yield "State left behind: the fixture did not remove what this request creates."
                                            + fixture;
                                } else if (success) {
                                    yield "The implementation answers with a status the contract does not declare for "
                                            + "this case, or the fixture set up the state for another declared status."
                                            + fixture;
                                } else if (failed) {
                                    yield "The implementation failed on a request the contract declares valid.";
                                }
                                yield null;
                            }
                            case "NOT_FOUND" -> {
                                if (success) {
                                    yield "The fixture did not remove the resource, or the implementation answers for "
                                            + "any identifier." + fixture;
                                } else if (received == 400) {
                                    yield "The implementation rejects an identifier the contract declares valid.";
                                }
                                yield null;
                            }
                            case "NOT_ACCEPTABLE" -> success
                                    ? "Content negotiation is not enforced: the implementation ignores Accept." : null;
                            case "UNSUPPORTED_MEDIA_TYPE" -> {
                                if (success) {
                                    yield "The implementation accepts a Content-Type the contract does not declare for "
                                            + "this request.";
                                } else if (received == 400) {
                                    yield "The implementation parsed the body before checking its media type.";
                                }
                                yield null;
                            }
                            default -> {
                                if (success) {
                                    yield "The implementation accepted a request the contract declares invalid: `"
                                            + contractCase.keyword() + "` at " + where(contractCase) + " is not enforced.";
                                } else if (received == 404) {
                                    yield "The implementation looked the resource up before validating the request. The "
                                            + "inbound adapter should reject contract violations before the port is called.";
                                } else if (received == 422 && contractCase.expectedStatus() == 400) {
                                    yield "A contract violation was treated as a domain violation. It should be rejected "
                                            + "by the adapter, not the domain.";
                                } else if (failed) {
                                    yield "The implementation failed instead of rejecting the request.";
                                }
                                yield null;
                            }
                        };
                    }

                    /** Where an invalid request's fault is: {@code body /emailAddress}, {@code the body}, {@code query page}. */
                    static String where(ContractCase contractCase) {
                        if (!contractCase.in().equals("body")) return contractCase.in() + " " + contractCase.name();
                        return contractCase.pointer() == null || contractCase.pointer().isEmpty()
                                ? "the body" : "body " + contractCase.pointer();
                    }

                    /**
                     * Fails, naming the case, unless the response's content type is compatible with one the
                     * case expects.
                     *
                     * @param contractCase the case
                     * @param contentTypes the response's {@code Content-Type} header values
                     */
                    public static void assertContentType(ContractCase contractCase, List<String> contentTypes) {
                        MediaType received = contentTypes == null || contentTypes.isEmpty() ? null
                                : MediaType.parseMediaType(contentTypes.get(0));
                        boolean compatible = received != null && contractCase.expectedContentTypes().stream()
                                .map(MediaType::parseMediaType).anyMatch(expected -> expected.isCompatibleWith(received));
                        if (!compatible) {
                            throw new AssertionError(subject(contractCase)
                                    + ": expected a content type compatible with " + contractCase.expectedContentTypes()
                                    + ", received " + (received == null ? "none" : received) + ".");
                        }
                    }
                }
                """.formatted(pkg, base, PREFIX, NOT_DOCUMENTATION.replace("%", "%%"));
    }

    /** A test method name from a case id, as the core converts it: the core keeps ids unique under it. */
    static String variableName(String text) {
        StringBuilder out = new StringBuilder();
        for (String word : words(text)) {
            if (out.isEmpty()) {
                out.append(Character.toLowerCase(word.charAt(0))).append(word.substring(1));
            } else {
                out.append(Character.toUpperCase(word.charAt(0))).append(word.substring(1));
            }
        }
        String name = out.isEmpty() ? "value" : out.toString();
        if (KEYWORDS.contains(name)) return name + "Value";
        return Character.isJavaIdentifierStart(name.charAt(0)) ? name : "value" + name;
    }

    /** The words of a name: split at anything not a letter or digit, and at lower-to-upper changes. */
    private static List<String> words(String text) {
        List<String> words = new ArrayList<>();
        StringBuilder word = new StringBuilder();
        for (int i = 0; i < text.length(); i++) {
            char c = text.charAt(i);
            if (!Character.isLetterOrDigit(c)) {
                flush(words, word);
                continue;
            }
            if (Character.isUpperCase(c) && !word.isEmpty() && Character.isLowerCase(word.charAt(word.length() - 1))) {
                flush(words, word);
            }
            word.append(c);
        }
        flush(words, word);
        return words;
    }

    private static void flush(List<String> words, StringBuilder word) {
        if (!word.isEmpty()) {
            words.add(word.toString());
            word.setLength(0);
        }
    }

    /**
     * A Java string literal. Control characters are written as octal escapes, which, unlike
     * Unicode escapes, cannot end the literal early.
     */
    static String literal(String value) {
        StringBuilder out = new StringBuilder().append(QUOTE);
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            if (c == QUOTE || c == BACKSLASH) {
                out.append(BACKSLASH).append(c);
            } else if (c == 10) {
                out.append(BACKSLASH).append('n');
            } else if (c == 13) {
                out.append(BACKSLASH).append('r');
            } else if (c < 0x20 || c == 0x7f) {
                out.append(BACKSLASH).append(String.format("%03o", (int) c));
            } else {
                out.append(c);
            }
        }
        return out.append(QUOTE).toString();
    }

    /** Text safe inside a Javadoc comment. */
    static String comment(String text) {
        return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                .replace("*/", "*&#47;").replace("@", "&#64;")
                .replace(String.valueOf(BACKSLASH), "&#92;");
    }
}
