package com.arc_e_tect.gradle.apionly.transcriberj.restdocs;

import com.arc_e_tect.gradle.apionly.transcriberj.model.Operation;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.EmitterContext;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.GeneratedClass;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.InvalidRequestCase;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/**
 * The invalid-request contract tests: per operation with cases, an interface of one test per
 * case; one support class they share; and one AsciiDoc file including each operation's
 * representative case.
 */
final class InvalidRequestTests {

    /** The emitter option that switches rendering on. */
    static final String OPTION = "tests";

    /** The shared support class. */
    static final String SUPPORT = "InvalidRequestContractSupport";

    /** What an interface's name ends with, after the operation's stem. */
    static final String SUFFIX = "InvalidRequestContractTests";

    /** What the core's invalid-request class names end with. */
    private static final String CORE_SUFFIX = "InvalidRequests";

    /** The snippet directory every test documents under, unless a test overrides it. */
    static final String PREFIX = "generated";

    private static final String INDENT = "    ";
    private static final String EXCLUDE_FROM_COVERAGE = "@com.arc_e_tect.sedr.utils.jacoco.marker"
            + ".ExcludeFromJacocoGeneratedCodeCoverage(justification = \"Generated by API-Only TranscriberJ\")\n";
    private static final char QUOTE = 34;
    private static final char BACKSLASH = 92;
    private static final Set<String> KEYWORDS = Set.of(
            "abstract", "assert", "boolean", "break", "byte", "case", "catch", "char", "class", "const",
            "continue", "default", "do", "double", "else", "enum", "extends", "final", "finally", "float",
            "for", "goto", "if", "implements", "import", "instanceof", "int", "interface", "long", "native",
            "new", "package", "private", "protected", "public", "return", "short", "static", "strictfp",
            "super", "switch", "synchronized", "this", "throw", "throws", "transient", "try", "void",
            "volatile", "while", "true", "false", "null", "var", "record", "yield", "sealed", "permits");

    /** The WebTestClient methods that start a request of a method, without naming it. */
    private static final Set<String> VERBS = Set.of("GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "OPTIONS");

    /** The verbs whose WebTestClient spec takes a body. */
    private static final Set<String> BODY_VERBS = Set.of("POST", "PUT", "PATCH");

    private InvalidRequestTests() {
    }

    /**
     * Whether the project switched rendering on. Only {@value #OPTION} is an option; any other
     * name is a mistake, and fails generation rather than being ignored.
     */
    static boolean enabled(Map<String, String> options) {
        for (String name : options.keySet()) {
            if (!name.equals(OPTION)) {
                throw new IllegalArgumentException("The REST Docs emitter has no option '" + name
                        + "'; its only option is '" + OPTION + "'.");
            }
        }
        return "true".equalsIgnoreCase(options.getOrDefault(OPTION, "false").trim());
    }

    /** Writes every interface, the support class when there is one, and the include file. */
    static void emit(EmitterContext context, String header, String pkg, String base) {
        List<Rendered> rendered = new ArrayList<>();
        for (Operation operation : context.model().operations()) {
            String location = location(operation);
            List<InvalidRequestCase> cases = context.invalidRequestCases(location);
            if (cases.isEmpty()) continue;
            GeneratedClass invalidRequests = context.names().invalidRequests(location).orElseThrow();
            GeneratedClass operationClass = context.names().operation(location).orElseThrow();
            String stem = invalidRequests.simpleName().endsWith(CORE_SUFFIX)
                    ? invalidRequests.simpleName().substring(0,
                    invalidRequests.simpleName().length() - CORE_SUFFIX.length())
                    : invalidRequests.simpleName();
            Rendered r = new Rendered(stem + SUFFIX, operation, operationClass.simpleName(),
                    invalidRequests.simpleName(), cases, documented(context));
            context.writeJava(pkg, r.name(), r.source(header, pkg, base));
            rendered.add(r);
        }
        if (rendered.isEmpty()) return;
        context.writeJava(pkg, SUPPORT, support(header, pkg, base));
        context.writeResource(includePath(context.settings().contract()),
                include(context.settings().contract(), context.model().version(), rendered));
    }

    /** Where the include file is written, relative to the resource root. */
    static String includePath(String contract) {
        return RestDocsEmitter.ID + "/" + contract + "-invalid-requests.adoc";
    }

    /** The operation's JSON pointer, as the core keys it. */
    private static String location(Operation operation) {
        return "/paths/" + operation.path().replace("~", "~0").replace("/", "~1") + "/" + operation.method().key();
    }

    /** The simple names of the classes that have a REST Docs companion. */
    private static Set<String> documented(EmitterContext context) {
        Set<String> out = new HashSet<>();
        for (GeneratedClass generated : context.names().all()) {
            if (generated.exposed() && generated.bodyShaped()) out.add(generated.simpleName());
        }
        return out;
    }

    /** One interface. */
    private record Rendered(String name, Operation operation, String operationClass, String casesClass,
                            List<InvalidRequestCase> cases, Set<String> documented) {

        String source(String header, String pkg, String base) {
            StringBuilder out = new StringBuilder(header);
            out.append("package ").append(pkg).append(";\n\n")
                    .append("import ").append(base).append(".InvalidRequestCase;\n")
                    .append("import ").append(base).append('.').append(casesClass).append(";\n")
                    .append("import ").append(base).append('.').append(operationClass).append(";\n")
                    .append("import org.junit.jupiter.api.DisplayName;\n")
                    .append("import org.junit.jupiter.api.Test;\n")
                    .append("import org.springframework.test.web.reactive.server.WebTestClient;\n\n")
                    .append("import static org.springframework.restdocs.webtestclient.WebTestClientRestDocumentation"
                            + ".document;\n\n");
            out.append("/**\n")
                    .append(" * Contract tests of operation ").append(comment(operation.method().name())).append(' ')
                    .append(comment(operation.path())).append(": one per case in {@link ").append(casesClass)
                    .append("},\n")
                    .append(" * each sending that invalid request exactly and expecting the response the contract\n")
                    .append(" * declares for it.\n")
                    .append(" *\n")
                    .append(" * <p>The tests are the same whichever implementation {@link #client()} is bound to: the\n")
                    .append(" * real one, or a double. Only {@link #arrangeInvalidRequest(InvalidRequestCase)} differs.\n")
                    .append(" */\n")
                    .append(EXCLUDE_FROM_COVERAGE)
                    .append("public interface ").append(name).append(" {\n\n");
            out.append(INDENT).append("/**\n")
                    .append(INDENT).append(" * The client the requests are sent with, bound to the implementation under test and\n")
                    .append(INDENT).append(" * configured for Spring REST Docs.\n")
                    .append(INDENT).append(" *\n")
                    .append(INDENT).append(" * @return the client\n")
                    .append(INDENT).append(" */\n")
                    .append(INDENT).append("WebTestClient client();\n\n");
            out.append(INDENT).append("/**\n")
                    .append(INDENT).append(" * Prepares the implementation under test for one invalid request, just before it is sent.\n")
                    .append(INDENT).append(" *\n")
                    .append(INDENT).append(" * <p>Empty, because the real implementation needs nothing: its inbound adapter rejects a\n")
                    .append(INDENT).append(" * contract violation before the port is called, so no state is consulted, and none needs\n")
                    .append(INDENT).append(" * arranging. A double, such as a WireMock stub, overrides it to answer the request as the\n")
                    .append(INDENT).append(" * contract declares.\n")
                    .append(INDENT).append(" *\n")
                    .append(INDENT).append(" * @param invalid the case about to be sent\n")
                    .append(INDENT).append(" */\n")
                    .append(INDENT).append("default void arrangeInvalidRequest(InvalidRequestCase invalid) {\n")
                    .append(INDENT).append("}\n\n");
            out.append(INDENT).append("/**\n")
                    .append(INDENT).append(" * The directory, under the snippets directory, every test documents in:\n")
                    .append(INDENT).append(" * {@code <prefix>/<operationId>/<caseId>}. Overridden by a variant whose snippets must\n")
                    .append(INDENT).append(" * not overwrite another's.\n")
                    .append(INDENT).append(" *\n")
                    .append(INDENT).append(" * @return the prefix; {@value ").append(SUPPORT)
                    .append("#DEFAULT_PREFIX} unless overridden\n")
                    .append(INDENT).append(" */\n")
                    .append(INDENT).append("default String generatedDocumentationPrefix() {\n")
                    .append(INDENT).append(INDENT).append("return ").append(SUPPORT).append(".DEFAULT_PREFIX;\n")
                    .append(INDENT).append("}\n");
            Set<String> methods = new HashSet<>();
            for (InvalidRequestCase c : cases) {
                String method = variableName(c.id()) + "_returns" + c.expectedStatus();
                if (!methods.add(method)) {
                    method = method + "_" + c.index();
                    methods.add(method);
                }
                test(out, c, method);
            }
            return out.append("}\n").toString();
        }

        private void test(StringBuilder out, InvalidRequestCase c, String method) {
            String verb = c.request().method().toUpperCase(Locale.ROOT);
            boolean body = c.request().body() != null;
            String display = verb + " " + operation.path() + ": " + c.description() + " returns "
                    + c.expectedStatus() + (c.representative() ? " [documented]" : "");
            String i2 = INDENT + INDENT;
            String i4 = i2 + i2;
            out.append('\n')
                    .append(INDENT).append("/** ").append(comment(c.description())).append(". */\n")
                    .append(INDENT).append("@Test\n")
                    .append(INDENT).append("@DisplayName(").append(literal(display)).append(")\n")
                    .append(INDENT).append("default void ").append(method).append("() {\n")
                    .append(i2).append("InvalidRequestCase invalid = ").append(casesClass).append(".CASES.get(")
                    .append(c.index()).append(");\n")
                    .append(i2).append("arrangeInvalidRequest(invalid);\n")
                    .append(i2).append(SUPPORT).append(".clientFor(client(), invalid)");
            if (VERBS.contains(verb) && (!body || BODY_VERBS.contains(verb))) {
                out.append('.').append(verb.toLowerCase(Locale.ROOT)).append("()\n");
            } else {
                out.append(".method(org.springframework.http.HttpMethod.valueOf(invalid.request().method()))\n");
            }
            out.append(i4).append(".uri(").append(operationClass).append(".PATH, ").append(SUPPORT)
                    .append(".pathValues(invalid))\n");
            if (!c.request().headers().isEmpty()) {
                out.append(i4).append(".headers(headers -> ").append(SUPPORT).append(".headers(headers, invalid))\n");
            }
            if (body) {
                out.append(i4).append(".contentType(").append(SUPPORT).append(".contentType(invalid))\n")
                        .append(i4).append(".bodyValue(").append(SUPPORT).append(".body(invalid))\n");
            }
            out.append(i4).append(".exchange()\n")
                    .append(i4).append(".expectBody()\n")
                    .append(i4).append(".consumeWith(result -> ").append(SUPPORT)
                    .append(".assertStatus(invalid, result.getStatus().value()))\n");
            if (!c.expectedContentTypes().isEmpty()) {
                out.append(i4).append(".consumeWith(result -> ").append(SUPPORT).append(".assertContentType(invalid,\n")
                        .append(i4).append(INDENT + INDENT)
                        .append("result.getResponseHeaders().get(org.springframework.http.HttpHeaders.CONTENT_TYPE)))\n");
            }
            out.append(i4).append(".consumeWith(document(").append(SUPPORT)
                    .append(".identifier(generatedDocumentationPrefix(),\n")
                    .append(i4).append(INDENT + INDENT + INDENT + INDENT)
                    .append(operation.operationId() != null ? operationClass + ".OPERATION_ID"
                            : SUPPORT + ".operationName(" + operationClass + ".class)")
                    .append(", invalid)");
            if (c.responseBodyClass() != null && documented.contains(c.responseBodyClass())) {
                out.append(",\n").append(i4).append(INDENT + INDENT).append(c.responseBodyClass())
                        .append("Docs.responseFields()");
            }
            out.append("));\n").append(INDENT).append("}\n");
        }

        /** The representative case: the one whose documentation is published. */
        InvalidRequestCase representative() {
            return cases.stream().filter(InvalidRequestCase::representative).findFirst().orElse(cases.get(0));
        }
    }

    /** The AsciiDoc file that includes the representative case of each operation. */
    private static String include(String contract, String version, List<Rendered> rendered) {
        StringBuilder out = new StringBuilder()
                .append("// Generated by the API-Only TranscriberJ REST Docs emitter from contract ").append(contract)
                .append(' ').append(version).append(".\n")
                .append("// Do not edit: this file is overwritten on every build.\n")
                .append("//\n")
                .append("// For each operation and status, the request and the response of one invalid request: the\n")
                .append("// representative case. The snippets are read from {invalid-request-snippets}, which is\n")
                .append("// {snippets}/").append(PREFIX).append(" unless the including document sets it -- as it must where\n")
                .append("// a test overrides generatedDocumentationPrefix().\n")
                .append("ifndef::invalid-request-snippets[:invalid-request-snippets: {snippets}/").append(PREFIX)
                .append("]\n");
        for (Rendered r : rendered) {
            InvalidRequestCase c = r.representative();
            String at = "{invalid-request-snippets}/" + operationId(r) + "/" + c.id() + "/";
            out.append("\n== ").append(operationId(r)).append(": ").append(c.expectedStatus()).append("\n\n")
                    .append("`+").append(r.operation().method().name()).append(' ').append(r.operation().path())
                    .append("+` -- ").append(asciidoc(c.description())).append(".\n\n")
                    .append(".Request\n")
                    .append("include::").append(at).append("http-request.adoc[]\n\n")
                    .append(".Response\n")
                    .append("include::").append(at).append("http-response.adoc[]\n");
            if (c.responseBodyClass() != null && r.documented().contains(c.responseBodyClass())) {
                out.append("\n.Response fields\n")
                        .append("include::").append(at).append("response-fields.adoc[]\n");
            }
        }
        return out.toString();
    }

    /**
     * The operation's snippet directory: its id, as its class's {@code OPERATION_ID} holds it, or,
     * for an operation without one, its class's name without {@code Operation}.
     */
    private static String operationId(Rendered r) {
        String id = r.operation().operationId();
        return id != null ? id : r.operationClass().substring(0, r.operationClass().length() - "Operation".length());
    }

    /** Text as AsciiDoc shows it literally: every attribute reference and markup character passed through. */
    private static String asciidoc(String text) {
        return "+" + text.replace("+", "{plus}") + "+";
    }

    /** The class every interface's tests share. */
    static String support(String header, String pkg, String base) {
        return header + """
                package %1$s;

                import %2$s.InvalidRequestCase;
                import org.springframework.http.HttpHeaders;
                import org.springframework.http.MediaType;
                import org.springframework.web.reactive.function.client.ClientRequest;
                import org.springframework.test.web.reactive.server.WebTestClient;

                import java.net.URI;
                import java.nio.charset.StandardCharsets;
                import java.util.List;
                import java.util.stream.Collectors;

                /**
                 * What the generated invalid-request contract tests share: sending a case's request exactly,
                 * and saying, when the response is not the one the contract declares, where to look.
                 */
                @com.arc_e_tect.sedr.utils.jacoco.marker.ExcludeFromJacocoGeneratedCodeCoverage(justification = "Generated by API-Only TranscriberJ")
                public final class InvalidRequestContractSupport {

                    /** The directory, under the snippets directory, the tests document in by default. */
                    public static final String DEFAULT_PREFIX = "%3$s";

                    private static final String UNRESERVED =
                            "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~";

                    private InvalidRequestContractSupport() {
                    }

                    /**
                     * The client to send a case's request with: the one given, or, where the request has query
                     * parameters, one that adds them to the URI exactly, since the operation's {@code PATH} is
                     * the whole URI template.
                     *
                     * @param client  the client under test
                     * @param invalid the case
                     * @return the client to send it with
                     */
                    public static WebTestClient clientFor(WebTestClient client, InvalidRequestCase invalid) {
                        if (invalid.request().query().isEmpty()) return client;
                        String query = query(invalid);
                        return client.mutate().filter((request, next) -> next.exchange(ClientRequest.from(request)
                                .url(withQuery(request.url(), query)).build())).build();
                    }

                    /**
                     * A URI with its query replaced.
                     *
                     * @param uri   the URI
                     * @param query the query, already encoded
                     * @return the URI with that query
                     */
                    static URI withQuery(URI uri, String query) {
                        return URI.create(uri.getScheme() + "://" + uri.getRawAuthority() + uri.getRawPath() + "?" + query);
                    }

                    /**
                     * A case's query parameters as a query string: every name and value percent-encoded as
                     * UTF-8, except the characters RFC 3986 leaves unreserved, so that a server decodes exactly
                     * the case's values -- {@code +} included.
                     *
                     * @param invalid the case
                     * @return the query, without {@code ?}
                     */
                    public static String query(InvalidRequestCase invalid) {
                        return invalid.request().query().stream()
                                .map(p -> encode(p.name()) + "=" + encode(p.value()))
                                .collect(Collectors.joining("&"));
                    }

                    /**
                     * A value percent-encoded as UTF-8, except the characters RFC 3986 leaves unreserved.
                     *
                     * @param value the value
                     * @return the encoded value
                     */
                    static String encode(String value) {
                        StringBuilder out = new StringBuilder();
                        for (byte b : value.getBytes(StandardCharsets.UTF_8)) {
                            if (b >= 0 && UNRESERVED.indexOf(b) >= 0) {
                                out.append((char) b);
                            } else {
                                out.append('%%').append(String.format("%%02X", b & 0xff));
                            }
                        }
                        return out.toString();
                    }

                    /**
                     * The values that fill the operation's path template, in order; the client encodes them.
                     *
                     * @param invalid the case
                     * @return the values
                     */
                    public static Object[] pathValues(InvalidRequestCase invalid) {
                        return invalid.request().pathParameters().toArray();
                    }

                    /**
                     * Adds a case's headers, exactly. A value that is not printable US-ASCII cannot be: HTTP
                     * header values are US-ASCII (RFC 9110), and HTTP clients replace or re-encode anything else,
                     * so the test fails before sending, rather than for a request the case does not describe.
                     *
                     * @param headers the request's headers
                     * @param invalid the case
                     */
                    public static void headers(HttpHeaders headers, InvalidRequestCase invalid) {
                        for (var header : invalid.request().headers()) {
                            if (!header.value().chars().allMatch(c -> c >= 0x20 && c < 0x7f)) {
                                throw new AssertionError("Case " + invalid.id() + " (" + invalid.description()
                                        + "): header " + header.name() + " holds '" + header.value() + "', which cannot "
                                        + "be sent as it is: HTTP header values are US-ASCII. Give the header's value in the "
                                        + "contract in US-ASCII.");
                            }
                            headers.add(header.name(), header.value());
                        }
                    }

                    /**
                     * A case's request content type.
                     *
                     * @param invalid the case
                     * @return the content type
                     */
                    public static MediaType contentType(InvalidRequestCase invalid) {
                        return MediaType.parseMediaType(invalid.request().contentType());
                    }

                    /**
                     * A case's request body, exactly: its bytes, so that no encoder rewrites it.
                     *
                     * @param invalid the case
                     * @return the body, as UTF-8
                     */
                    public static byte[] body(InvalidRequestCase invalid) {
                        return invalid.request().body().getBytes(StandardCharsets.UTF_8);
                    }

                    /**
                     * The name of an operation the contract gives no {@code operationId}: its class's simple
                     * name, without {@code Operation}.
                     *
                     * @param operationClass the operation's class
                     * @return the name
                     */
                    public static String operationName(Class<?> operationClass) {
                        String name = operationClass.getSimpleName();
                        return name.endsWith("Operation") ? name.substring(0, name.length() - "Operation".length()) : name;
                    }

                    /**
                     * Where a case's snippets are written: {@code <prefix>/<operationId>/<caseId>}.
                     *
                     * @param prefix      the prefix
                     * @param operationId the operation's id
                     * @param invalid     the case
                     * @return the REST Docs identifier
                     */
                    public static String identifier(String prefix, String operationId, InvalidRequestCase invalid) {
                        return prefix + "/" + operationId + "/" + invalid.id();
                    }

                    /**
                     * Fails, saying where to look, unless the status received is the one the case expects.
                     *
                     * @param invalid  the case
                     * @param received the status received
                     */
                    public static void assertStatus(InvalidRequestCase invalid, int received) {
                        if (received != invalid.expectedStatus()) {
                            throw new AssertionError(statusMessage(invalid, received));
                        }
                    }

                    /**
                     * What a status other than the expected one says about the implementation.
                     *
                     * @param invalid  the case
                     * @param received the status received
                     * @return the message
                     */
                    public static String statusMessage(InvalidRequestCase invalid, int received) {
                        String subject = "Case " + invalid.id() + " (" + invalid.description() + "; "
                                + invalid.keyword() + " at " + where(invalid) + "): expected "
                                + invalid.expectedStatus() + ", received " + received + ".";
                        String cause;
                        if (received >= 200 && received < 300) {
                            cause = "The implementation accepted a request the contract declares invalid: `"
                                    + invalid.keyword() + "` at " + where(invalid) + " is not enforced.";
                        } else if (received == 404) {
                            cause = "The implementation looked the resource up before validating the request. The "
                                    + "inbound adapter should reject contract violations before the port is called.";
                        } else if (received == 422 && invalid.expectedStatus() == 400) {
                            cause = "A contract violation was treated as a domain violation. It should be rejected "
                                    + "by the adapter, not the domain.";
                        } else if (received >= 500 && received < 600) {
                            cause = "The implementation failed instead of rejecting the request.";
                        } else {
                            return subject;
                        }
                        return subject + " " + cause;
                    }

                    /** Where a case's fault is: {@code body /emailAddress}, {@code the body}, {@code query page}. */
                    static String where(InvalidRequestCase invalid) {
                        if (!invalid.in().equals("body")) return invalid.in() + " " + invalid.name();
                        return invalid.pointer() == null || invalid.pointer().isEmpty()
                                ? "the body" : "body " + invalid.pointer();
                    }

                    /**
                     * Fails, naming the case, unless the response's content type is compatible with one the
                     * case expects.
                     *
                     * @param invalid      the case
                     * @param contentTypes the response's {@code Content-Type} header values
                     */
                    public static void assertContentType(InvalidRequestCase invalid, List<String> contentTypes) {
                        MediaType received = contentTypes == null || contentTypes.isEmpty() ? null
                                : MediaType.parseMediaType(contentTypes.get(0));
                        boolean compatible = received != null && invalid.expectedContentTypes().stream()
                                .map(MediaType::parseMediaType).anyMatch(expected -> expected.isCompatibleWith(received));
                        if (!compatible) {
                            throw new AssertionError("Case " + invalid.id() + " (" + invalid.description()
                                    + "): expected a content type compatible with " + invalid.expectedContentTypes()
                                    + ", received " + (received == null ? "none" : received) + ".");
                        }
                    }
                }
                """.formatted(pkg, base, PREFIX);
    }

    /** A test method name from a case id, as the core converts it: the core keeps ids unique under it. */
    static String variableName(String text) {
        StringBuilder out = new StringBuilder();
        for (String word : words(text)) {
            if (out.isEmpty()) {
                out.append(Character.toLowerCase(word.charAt(0))).append(word.substring(1));
            } else {
                out.append(Character.toUpperCase(word.charAt(0))).append(word.substring(1));
            }
        }
        String name = out.isEmpty() ? "value" : out.toString();
        if (KEYWORDS.contains(name)) return name + "Value";
        return Character.isJavaIdentifierStart(name.charAt(0)) ? name : "value" + name;
    }

    /** The words of a name: split at anything not a letter or digit, and at lower-to-upper changes. */
    private static List<String> words(String text) {
        List<String> words = new ArrayList<>();
        StringBuilder word = new StringBuilder();
        for (int i = 0; i < text.length(); i++) {
            char c = text.charAt(i);
            if (!Character.isLetterOrDigit(c)) {
                flush(words, word);
                continue;
            }
            if (Character.isUpperCase(c) && !word.isEmpty() && Character.isLowerCase(word.charAt(word.length() - 1))) {
                flush(words, word);
            }
            word.append(c);
        }
        flush(words, word);
        return words;
    }

    private static void flush(List<String> words, StringBuilder word) {
        if (!word.isEmpty()) {
            words.add(word.toString());
            word.setLength(0);
        }
    }

    /**
     * A Java string literal. Control characters are written as octal escapes, which, unlike
     * Unicode escapes, cannot end the literal early.
     */
    static String literal(String value) {
        StringBuilder out = new StringBuilder().append(QUOTE);
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            if (c == QUOTE || c == BACKSLASH) {
                out.append(BACKSLASH).append(c);
            } else if (c == 10) {
                out.append(BACKSLASH).append('n');
            } else if (c == 13) {
                out.append(BACKSLASH).append('r');
            } else if (c < 0x20 || c == 0x7f) {
                out.append(BACKSLASH).append(String.format("%03o", (int) c));
            } else {
                out.append(c);
            }
        }
        return out.append(QUOTE).toString();
    }

    /** Text safe inside a Javadoc comment. */
    static String comment(String text) {
        return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                .replace("*/", "*&#47;").replace("@", "&#64;")
                .replace(String.valueOf(BACKSLASH), "&#92;");
    }
}
