package com.arc_e_tect.gradle.apionly.transcriberj.restdocs;

import com.arc_e_tect.gradle.apionly.transcriberj.model.Construct;
import com.arc_e_tect.gradle.apionly.transcriberj.model.Schema;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.Emitter;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.EmitterContext;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.GeneratedClass;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.ManagedDependency;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.Origin;

import java.util.EnumSet;
import java.util.List;
import java.util.Set;

/**
 * Spring REST Docs companions for the classes the API-Only TranscriberJ generates.
 *
 * <p>For every public core class with a body, {@code <basePackage>.restdocs.<Name>Docs}
 * holds its field descriptors and its request and response field snippets. A body
 * whose contract allows members it does not list gets relaxed snippets, which do
 * not fail on undocumented fields.
 */
public final class RestDocsEmitter implements Emitter {

    /** The emitter's identifier, and the package its companions go in. */
    public static final String ID = "restdocs";

    /** Creates the emitter, as {@link java.util.ServiceLoader} does. */
    public RestDocsEmitter() {
    }

    @Override
    public String id() {
        return ID;
    }

    @Override
    public List<ManagedDependency> dependencies() {
        return List.of(new ManagedDependency("org.springframework.restdocs", "spring-restdocs-core", "4.0.1", "5"));
    }

    /**
     * Everything the core classes represent: a companion only turns their field
     * descriptions into descriptors, so where the core degrades, the companion
     * throws the core's reason.
     */
    @Override
    public Set<Construct> represents() {
        return EnumSet.complementOf(EnumSet.of(Construct.MULTIPLE_TYPES, Construct.BOOLEAN_SCHEMA,
                Construct.ONE_OF_INLINE_BRANCHES, Construct.ANY_OF_INLINE_BRANCHES,
                Construct.UNMODELLED_KEYWORD, Construct.UNMODELLED_COMPONENT_TYPE));
    }

    @Override
    public void emit(EmitterContext context) {
        String base = context.settings().basePackage();
        String pkg = base + "." + ID;
        String header = "// Generated by the API-Only TranscriberJ REST Docs emitter from contract "
                + context.settings().contract() + " " + context.model().version() + ".\n"
                + "// Do not edit: this file is overwritten on every build.\n";
        context.writeJava(pkg, "RestDocsFields", Sources.fields(header, pkg, base));
        for (GeneratedClass generated : context.names().all()) {
            if (!generated.exposed() || !generated.bodyShaped()) continue;
            context.writeJava(pkg, generated.simpleName() + "Docs",
                    Sources.companion(header, pkg, base, generated.simpleName(), openness(context, generated)));
        }
    }

    /** The class whose {@code OPEN} says whether this class's bodies are open. */
    private static String openness(EmitterContext context, GeneratedClass generated) {
        Schema schema = generated.schema();
        boolean delegates = generated.origin() != Origin.SCHEMA && schema.ref() != null
                && schema.types() == null && schema.properties() == null;
        if (!delegates) return generated.simpleName();
        return context.names().component(Origin.SCHEMA, schema.ref()).orElseThrow().simpleName();
    }
}
