[versions]
api-only-transcriberj = "0.3.3"
api-only-transcriberj-restdocs = "0.1.1"
spring-boot = "4.1.1"

[libraries]
api-only-transcriberj-restdocs = { module = "com.arc-e-tect:api-only-transcriberj-restdocs", version.ref = "api-only-transcriberj-restdocs" }

[plugins]
api-only-transcriberj = { id = "com.arc-e-tect.api-only-transcriberj", version.ref = "api-only-transcriberj" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
