[versions]
api-only-transcriberj = "0.3.2"
api-only-transcriberj-restdocs = "0.1.1"
junit = "6.1.3"
assertj = "3.27.7"

[libraries]
api-only-transcriberj-restdocs = { module = "com.arc-e-tect:api-only-transcriberj-restdocs", version.ref = "api-only-transcriberj-restdocs" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }

[plugins]
api-only-transcriberj = { id = "com.arc-e-tect.api-only-transcriberj", version.ref = "api-only-transcriberj" }
