package com.arc_e_tect.gradle.apionly.transcriberj.wiremock;

import java.util.List;

/** The source of the class the WireMock emitter generates. */
final class Sources {

    /** The generated class's simple name. */
    static final String STUBS = "InvalidRequestStubs";

    private static final String INDENT = "    ";

    private Sources() {
    }

    /**
     * {@code InvalidRequestStubs}: one method that turns any invalid-request case into a WireMock
     * mapping matching exactly that case's request.
     *
     * <p>Every element of the request is matched: the method; the path, filled with the case's
     * values percent-encoded as they travel; each query parameter and header the case sends, and
     * each one its operation declares that the case leaves out, as absent; the content type,
     * allowing a {@code charset} parameter; and the body as JSON, arrays in order and no member
     * more or less, or its absence. Headers the operation does not declare -- {@code Accept},
     * {@code Authorization}, whatever a project's client adds -- are not matched, so a project's
     * default client headers never stop a stub from matching. The mapping answers with the case's
     * status and, where the declared response has content, its first content type and the
     * response class's {@code requiredBody()}.
     *
     * <p>Every value comes from the case at run time; the body class is chosen by name from
     * those the contract's cases answer with, so the source holds no request value and no JSON.
     *
     * @param header      the comment every generated file starts with
     * @param pkg         the package it goes in
     * @param base        the base package, where the core's classes are
     * @param priority    the mappings' priority
     * @param bodyClasses the simple names of the response body classes the cases answer with
     * @return the source
     */
    static String stubs(String header, String pkg, String base, int priority, List<String> bodyClasses) {
        String i2 = INDENT + INDENT;
        StringBuilder bodies = new StringBuilder();
        if (bodyClasses.isEmpty()) {
            // No case answers with a body, so this is never called; a switch needs a case.
            bodies.append(i2).append(unknown(i2));
        } else {
            bodies.append(i2).append("return switch (bodyClass) {\n");
            for (String bodyClass : bodyClasses) {
                bodies.append(i2).append(INDENT).append("case \"").append(bodyClass).append("\" -> ").append(base)
                        .append('.').append(bodyClass).append(".requiredBody();\n");
            }
            bodies.append(i2).append(INDENT).append("default -> ").append(unknown(i2 + INDENT)).append(i2).append("};\n");
        }
        return header + """
                package %1$s;

                import %2$s.ContractRequest;
                import %2$s.InvalidRequestCase;
                import com.github.tomakehurst.wiremock.client.MappingBuilder;
                import com.github.tomakehurst.wiremock.client.ResponseDefinitionBuilder;
                import com.github.tomakehurst.wiremock.client.WireMock;

                import java.nio.charset.StandardCharsets;
                import java.util.ArrayList;
                import java.util.LinkedHashMap;
                import java.util.List;
                import java.util.Map;
                import java.util.regex.Matcher;
                import java.util.regex.Pattern;

                /**
                 * WireMock stubs for the contract's invalid-request cases, so that the contract tests that send
                 * those cases run unchanged against a WireMock double. A test's fixture hook registers its case's
                 * mapping on whichever WireMock it reaches:
                 *
                 * <pre>{@code
                 * wireMockServer.stubFor(InvalidRequestStubs.mappingFor(invalid));   // an in-process server
                 * WireMock.stubFor(InvalidRequestStubs.mappingFor(invalid));         // the static client
                 * new WireMock(host, port).register(InvalidRequestStubs.mappingFor(invalid));
                 * }</pre>
                 *
                 * <p>A mapping matches exactly its case's request, and nothing looser: a stub that matched more
                 * would make other tests pass for the wrong reason, and one that matched a valid request would
                 * answer the hand-written happy-path tests sharing the server. It has priority {@value #PRIORITY},
                 * so a project's own, looser stub for the same method and path at WireMock's default priority
                 * never answers a request the contract declares invalid in its place.
                 */
                @com.arc_e_tect.sedr.utils.jacoco.marker.ExcludeFromJacocoGeneratedCodeCoverage(justification = "Generated by API-Only TranscriberJ")
                public final class InvalidRequestStubs {

                    /** The priority of every mapping: higher than WireMock's default, so that no looser stub wins. */
                    public static final int PRIORITY = %3$d;

                    private static final String UNRESERVED =
                            "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~";
                    private static final Pattern PLACEHOLDER = Pattern.compile("\\\\{[^}]+}");

                    private InvalidRequestStubs() {
                    }

                    /**
                     * A mapping that matches exactly the case's request and answers as the contract declares for it.
                     * It is named {@code <operationId>/<caseId>} -- {@code <METHOD> <path>/<caseId>} for an operation
                     * without an id -- so that WireMock's near-miss reports and request journal say which case a
                     * stub belongs to.
                     *
                     * @param invalid the case
                     * @return the mapping, to register on a WireMock server or client
                     */
                    public static MappingBuilder mappingFor(InvalidRequestCase invalid) {
                        ContractRequest request = invalid.request();
                        MappingBuilder mapping = WireMock.request(request.method(), WireMock.urlPathEqualTo(path(request)))
                                .withName(name(invalid))
                                .atPriority(PRIORITY);
                        Map<String, List<String>> query = new LinkedHashMap<>();
                        for (ContractRequest.Pair parameter : request.query()) {
                            query.computeIfAbsent(parameter.name(), name -> new ArrayList<>()).add(parameter.value());
                        }
                        for (Map.Entry<String, List<String>> parameter : query.entrySet()) {
                            mapping = mapping.withQueryParam(parameter.getKey(),
                                    WireMock.havingExactly(parameter.getValue().toArray(String[]::new)));
                        }
                        for (String name : invalid.declaredQuery()) {
                            if (!query.containsKey(name)) mapping = mapping.withQueryParam(name, WireMock.absent());
                        }
                        List<String> sent = new ArrayList<>();
                        for (ContractRequest.Pair header : request.headers()) {
                            mapping = mapping.withHeader(header.name(), WireMock.equalTo(header.value()));
                            sent.add(header.name());
                        }
                        for (String name : invalid.declaredHeaders()) {
                            if (sent.stream().noneMatch(name::equalsIgnoreCase)) {
                                mapping = mapping.withHeader(name, WireMock.absent());
                            }
                        }
                        if (request.body() == null) {
                            mapping = mapping.withRequestBody(WireMock.absent());
                        } else {
                            mapping = mapping
                                    .withHeader("Content-Type", WireMock.matching("(?i)" + Pattern.quote(request.contentType())
                                            + "(\\\\s*;\\\\s*charset=[^;]+)?"))
                                    .withRequestBody(WireMock.equalToJson(request.body(), false, false));
                        }
                        return mapping.willReturn(response(invalid));
                    }

                    /** What the contract declares the response to the case is. */
                    private static ResponseDefinitionBuilder response(InvalidRequestCase invalid) {
                        ResponseDefinitionBuilder response = WireMock.aResponse().withStatus(invalid.expectedStatus());
                        if (invalid.expectedContentTypes().isEmpty()) return response;
                        response = response.withHeader("Content-Type", invalid.expectedContentTypes().get(0));
                        if (invalid.responseBodyClass() == null) return response;
                        return response.withBody(body(invalid.responseBodyClass()));
                    }

                    /** A valid body of a response body class, by the class's simple name. */
                    private static String body(String bodyClass) {
                %4$s    }

                    /** The mapping's name: {@code <operationId>/<caseId>}. */
                    private static String name(InvalidRequestCase invalid) {
                        String operation = invalid.operationId() != null ? invalid.operationId()
                                : invalid.request().method() + " " + invalid.request().pathTemplate();
                        return operation + "/" + invalid.id();
                    }

                    /** The path as the request travels: the template filled with the values, each percent-encoded. */
                    private static String path(ContractRequest request) {
                        Matcher placeholder = PLACEHOLDER.matcher(request.pathTemplate());
                        StringBuilder out = new StringBuilder();
                        int i = 0;
                        while (placeholder.find()) {
                            placeholder.appendReplacement(out,
                                    Matcher.quoteReplacement(encode(request.pathParameters().get(i++))));
                        }
                        placeholder.appendTail(out);
                        return out.toString();
                    }

                    /** A value percent-encoded as UTF-8, except the characters RFC 3986 leaves unreserved. */
                    private static String encode(String value) {
                        StringBuilder out = new StringBuilder();
                        for (byte b : value.getBytes(StandardCharsets.UTF_8)) {
                            if (b >= 0 && UNRESERVED.indexOf(b) >= 0) {
                                out.append((char) b);
                            } else {
                                out.append('%%').append(String.format(java.util.Locale.ROOT, "%%02X", b & 0xff));
                            }
                        }
                        return out.toString();
                    }
                }
                """.formatted(pkg, base, priority, bodies);
    }

    /** The statement for a body class no case answers with, its continuation indented from where it starts. */
    private static String unknown(String indent) {
        return "throw new IllegalArgumentException(\"No response body class \" + bodyClass\n"
                + indent + INDENT + INDENT + "+ \" in this contract's invalid-request cases.\");\n";
    }
}
