package com.arc_e_tect.gradle.apionly.transcriberj.wiremock;

import com.arc_e_tect.gradle.apionly.transcriberj.model.Construct;
import com.arc_e_tect.gradle.apionly.transcriberj.model.Operation;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.Emitter;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.EmitterContext;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.InvalidRequestCase;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.ManagedDependency;

import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * Exact WireMock stubs for the invalid-request cases the API-Only TranscriberJ derives.
 *
 * <p>{@code <basePackage>.wiremock.InvalidRequestStubs.mappingFor(InvalidRequestCase)} gives, for
 * any case, a stub that matches exactly that case's request and answers as the contract declares:
 * the case's status, the declared content type, and a valid body. A contract test written
 * against the real implementation then runs unchanged against a WireMock double, its fixture
 * hook registering the case's stub. See {@link Sources#stubs} for what is matched and why.
 *
 * <p>The stubs are generated only when at least one operation has a case. They depend on
 * WireMock, and so, like everything the TranscriberJ generates, are compiled only into the
 * source sets the subscription names: test source sets, never {@code main}.
 */
public final class WireMockEmitter implements Emitter {

    /** The emitter's identifier, and the package its stubs go in. */
    public static final String ID = "wiremock";

    /** The option that sets the stubs' priority. */
    static final String PRIORITY = "priority";

    /** The priority the stubs have unless the option sets another: WireMock's highest. */
    static final int DEFAULT_PRIORITY = 1;

    /** Creates the emitter, as {@link java.util.ServiceLoader} does. */
    public WireMockEmitter() {
    }

    @Override
    public String id() {
        return ID;
    }

    /**
     * WireMock's stubbing API, in the artifact {@code wiremock-spring-boot} 4.x brings -- the
     * WireMock core on Jetty 12 -- so that a project using it resolves nothing new.
     */
    @Override
    public List<ManagedDependency> dependencies() {
        return List.of(new ManagedDependency("org.wiremock", "wiremock-jetty12", "3.13.2", "4"));
    }

    /**
     * Nothing: the stubs are generated from the core's invalid-request cases, not from a schema
     * construct a core class represents.
     */
    @Override
    public Set<Construct> represents() {
        return Set.of();
    }

    @Override
    public void emit(EmitterContext context) {
        int priority = priority(context.settings().emitterOptions(ID));
        Set<String> bodyClasses = new TreeSet<>();
        boolean any = false;
        for (Operation operation : context.model().operations()) {
            for (InvalidRequestCase c : context.invalidRequestCases(location(operation))) {
                any = true;
                if (c.responseBodyClass() != null && !c.expectedContentTypes().isEmpty()) {
                    bodyClasses.add(c.responseBodyClass());
                }
            }
        }
        if (!any) return;

        String base = context.settings().basePackage();
        String pkg = base + "." + ID;
        String header = "// Generated by the API-Only TranscriberJ WireMock emitter from contract "
                + context.settings().contract() + " " + context.model().version() + ".\n"
                + "// Do not edit: this file is overwritten on every build.\n";
        context.writeJava(pkg, Sources.STUBS, Sources.stubs(header, pkg, base, priority, List.copyOf(bodyClasses)));
    }

    /**
     * The stubs' priority. Only {@value #PRIORITY} is an option; any other name, and any value
     * that is not a positive whole number, is a mistake, and fails generation rather than being
     * ignored.
     */
    static int priority(Map<String, String> options) {
        for (String name : options.keySet()) {
            if (!name.equals(PRIORITY)) {
                throw new IllegalArgumentException("The WireMock emitter has no option '" + name
                        + "'; its only option is '" + PRIORITY + "'.");
            }
        }
        String value = options.get(PRIORITY);
        if (value == null) return DEFAULT_PRIORITY;
        try {
            int priority = Integer.parseInt(value.trim());
            if (priority >= 1) return priority;
        } catch (NumberFormatException e) {
            // Reported below, with what is expected.
        }
        throw new IllegalArgumentException("The WireMock emitter's option '" + PRIORITY + "' is '" + value
                + "'; it must be a whole number of 1 or more, WireMock's highest priority being 1.");
    }

    /** The operation's JSON pointer, as the core keys it. */
    private static String location(Operation operation) {
        return "/paths/" + operation.path().replace("~", "~0").replace("/", "~1") + "/" + operation.method().key();
    }
}
