package com.arc_e_tect.gradle.apionly.transcriberj.microcks;

import com.arc_e_tect.gradle.apionly.transcriberj.model.AsyncChannel;
import com.arc_e_tect.gradle.apionly.transcriberj.model.AsyncOperation;
import com.arc_e_tect.gradle.apionly.transcriberj.model.Construct;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.Emitter;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.EmitterContext;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.GeneratedClass;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.ManagedDependency;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.Origin;

import java.util.List;
import java.util.Set;
import java.util.regex.Pattern;

/**
 * A JUnit 5 harness that checks what a service publishes against a Microcks-imported
 * copy of its AsyncAPI contract.
 *
 * <p>For every {@code send} operation of the contract's AsyncAPI document, {@code
 * AsyncConformanceHarness} carries a generated {@code @Test} that publishes a message
 * through the application and asks Microcks whether it conforms. What a generator
 * cannot know -- how the application actually publishes, which broker it uses, and
 * where the fetched contract document sits in the project's build -- is left to
 * abstract methods the project implements. See {@link Sources#harness} for what is
 * generated and what is asked of the project.
 *
 * <p>{@code receive} operations are not represented yet: verifying that an application
 * correctly reacts to a message it received needs a different harness shape, and is
 * left for a later emitter.
 *
 * <p><b>Testcontainers 2.x:</b> {@code microcks-testcontainers} 0.5.0 is built against
 * the Testcontainers 2.x line. Gradle resolves Testcontainers core to the highest version
 * anything asks for, so a project that pins 1.x for core still gets 2.x. In the reference
 * implementation that was core 2.0.5 beside the 1.21.4 Kafka module, and the generated
 * tests passed; other combinations are untested. A project that pins Testcontainers
 * should check what its build resolves.
 */
public final class MicrocksEmitter implements Emitter {

    /** The emitter's identifier, and the package its harness goes in. */
    public static final String ID = "microcks";

    /**
     * A send operation's {@code operationId} becomes the name of the hook the project
     * implements to publish it, and of the {@code @Test} that checks it, so it must
     * already be a valid Java identifier. AsyncAPI operation ids conventionally are.
     */
    private static final Pattern JAVA_IDENTIFIER = Pattern.compile("[a-zA-Z_$][a-zA-Z0-9_$]*");

    /** Creates the emitter, as {@link java.util.ServiceLoader} does. */
    public MicrocksEmitter() {
    }

    @Override
    public String id() {
        return ID;
    }

    @Override
    public List<ManagedDependency> dependencies() {
        // microcks-testcontainers 0.5.0 is built against the Testcontainers 2.x line; see
        // the class Javadoc. No broker-specific Testcontainers module is declared here:
        // which broker a project publishes over is the harness's own choice, made in
        // wireBroker(...).
        return List.of(
                new ManagedDependency("io.github.microcks", "microcks-testcontainers", "0.5.0", "0.6.0"),
                new ManagedDependency("org.testcontainers", "testcontainers", "2.0.5", "2.1.0"));
    }

    /**
     * Nothing: the harness is generated from the AsyncAPI document's operations and
     * channels, not from a schema construct a core class represents.
     */
    @Override
    public Set<Construct> represents() {
        return Set.of();
    }

    @Override
    public void emit(EmitterContext context) {
        List<AsyncOperation> sends = context.model().asyncOperations().stream()
                .filter(operation -> "send".equals(operation.action()))
                .toList();
        if (sends.isEmpty()) return;

        String base = context.settings().basePackage();
        String pkg = base + "." + ID;
        String header = "// Generated by the API-Only TranscriberJ Microcks emitter from contract "
                + context.settings().contract() + " " + context.model().version() + ".\n"
                + "// Do not edit: this file is overwritten on every build.\n";

        List<Sources.SendOperation> operations = sends.stream().map(operation -> {
            if (!JAVA_IDENTIFIER.matcher(operation.operationId()).matches()) {
                throw new IllegalStateException("AsyncAPI operation " + operation.operationId() + " at "
                        + operation.location() + " cannot be a Java identifier, so the Microcks emitter cannot "
                        + "name a hook or a test after it. Rename the operation in the contract.");
            }
            AsyncChannel channel = context.model().channels().stream()
                    .filter(c -> c.key().equals(operation.channelKey())).findFirst().orElse(null);
            if (channel == null || channel.address() == null) {
                throw new IllegalStateException("AsyncAPI operation " + operation.operationId() + " at "
                        + operation.location() + " has no channel address, so the Microcks emitter cannot "
                        + "generate an isolated channel identifier for its test. Give the channel an address.");
            }
            GeneratedClass generated = context.names().operation(operation.location())
                    .filter(g -> g.origin() == Origin.ASYNC_OPERATION)
                    .orElseThrow(() -> new IllegalStateException(
                            "No generated class for AsyncAPI operation " + operation.operationId()
                                    + " at " + operation.location() + ": the core emitter did not run first."));
            return new Sources.SendOperation(operation.operationId(), generated.simpleName());
        }).toList();

        context.writeResource("META-INF/apionly/microcks/" + context.settings().contract() + ".properties",
                Sources.contractProperties(context.model().asyncTitle()));
        context.writeJava(pkg, "AsyncConformanceHarness",
                Sources.harness(header, pkg, base, context.settings().contract(), operations));
    }
}
