package com.arc_e_tect.gradle.apionly.transcriberj.microcks;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Properties;

/** The Java source and the properties resource the emitter writes. */
final class Sources {

    /** The Microcks image this emitter was tested with; the properties file's default. */
    private static final String DEFAULT_MICROCKS_IMAGE = "quay.io/microcks/microcks-uber:1.13.2";

    private Sources() {
    }

    /**
     * One {@code send} operation the generated harness carries a hook and a test for.
     *
     * @param operationId    the operation's id, and the name of the hook and the test
     *                       method root
     * @param operationClass the simple name of the core class the TranscriberJ
     *                       generated for it, which carries {@code OPERATION_ID} and
     *                       {@code CHANNEL_ADDRESS}
     */
    record SendOperation(String operationId, String operationClass) {
    }

    /**
     * The contract's identity, as a {@code .properties} resource the generated harness
     * reads at runtime: {@code asyncapi.service.name}, the {@code info.title} Microcks
     * imports the contract's service under, and {@code microcks.image}, the image this
     * emitter was tested with. Written with {@link Properties#store}, so it reads back
     * with {@link Properties#load} exactly, whatever characters {@code title} holds.
     *
     * @param title the AsyncAPI document's own {@code info.title} -- not the OpenAPI
     *              document's, which Microcks does not import the async service
     *              under -- or {@code null} when it has none
     * @return the resource's content
     */
    static String contractProperties(String title) {
        Properties properties = new Properties();
        properties.setProperty("asyncapi.service.name", title == null ? "" : title);
        properties.setProperty("microcks.image", DEFAULT_MICROCKS_IMAGE);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            properties.store(out, "Generated by the API-Only TranscriberJ Microcks emitter. "
                    + "Do not edit: this file is overwritten on every build.");
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        return out.toString(StandardCharsets.ISO_8859_1);
    }

    /**
     * The {@code AsyncConformanceHarness} interface: one generated {@code @Test} and
     * one abstract hook per send operation, the Microcks ensemble's lifecycle, and the
     * three hooks every harness needs whatever operations it carries.
     *
     * @param header       the file's generated-code banner
     * @param pkg          the package the harness goes in, {@code <base>.microcks}
     * @param base         the base package the core classes were generated into
     * @param contract     the contract's name, as the project subscribed to it
     * @param operations   every {@code send} operation, in contract order
     * @return the compilation unit
     */
    static String harness(String header, String pkg, String base, String contract,
                          List<SendOperation> operations) {
        StringBuilder imports = new StringBuilder();
        StringBuilder members = new StringBuilder();
        for (SendOperation operation : operations) {
            imports.append("import ").append(base).append('.').append(operation.operationClass()).append(";\n");
            members.append(hook(operation)).append('\n').append(test(operation)).append('\n');
        }

        return header + """
                package %1$s;

                %2$s\
                import io.github.microcks.testcontainers.MicrocksContainersEnsemble;
                import io.github.microcks.testcontainers.MicrocksException;
                import io.github.microcks.testcontainers.model.ServiceRef;
                import io.github.microcks.testcontainers.model.TestRequest;
                import io.github.microcks.testcontainers.model.TestResult;
                import io.github.microcks.testcontainers.model.TestRunnerType;
                import org.junit.jupiter.api.AfterAll;
                import org.junit.jupiter.api.Assertions;
                import org.junit.jupiter.api.BeforeAll;
                import org.junit.jupiter.api.Test;
                import org.junit.jupiter.api.TestInstance;
                import org.testcontainers.containers.Network;

                import java.io.IOException;
                import java.io.InputStream;
                import java.io.UncheckedIOException;
                import java.nio.file.Path;
                import java.time.Duration;
                import java.util.List;
                import java.util.Properties;
                import java.util.UUID;
                import java.util.concurrent.TimeUnit;
                import java.util.concurrent.atomic.AtomicReference;

                /**
                 * Checks that what this application publishes conforms to the {@code send}
                 * operations of contract %3$s.
                 *
                 * <p><b>What is generated:</b> one {@code @Test} per operation, below, and the
                 * Microcks ensemble's lifecycle. {@link #SERVICE_NAME} and {@link #MICROCKS_IMAGE}
                 * are read from a properties file this emitter also generates, so either can
                 * change without regenerating this interface.
                 *
                 * <p><b>What the implementing class must supply:</b>
                 * <ul>
                 * <li>{@link #wireBroker(MicrocksContainersEnsemble)}: start this application's
                 * message broker on {@code ensemble.getNetwork()}, and connect the ensemble to it,
                 * before the ensemble starts.
                 * <li>{@link #contractFile()}: where the build put the fetched AsyncAPI document,
                 * for Microcks to import. The emitter cannot know this: it depends on the
                 * project's own build layout.
                 * <li>{@link #endpoint(String)}: turn a generated, isolation-suffixed channel
                 * address into the endpoint Microcks tests against, in the broker's own address
                 * form.
                 * <li>one hook per operation, named after its {@code operationId}, that publishes
                 * a message on the suffixed channel through the application, exactly as
                 * production code would.
                 * </ul>
                 *
                 * <p>The implementing class runs with {@link TestInstance.Lifecycle#PER_CLASS}:
                 * one Microcks ensemble for every test this interface declares, not one per test,
                 * so {@link #wireBroker} and {@link #contractFile} run once, before any
                 * operation's test.
                 */
                @TestInstance(TestInstance.Lifecycle.PER_CLASS)
                public interface AsyncConformanceHarness {

                    /** Where the emitter wrote this contract's identity; see {@link #CONTRACT}. */
                    String CONTRACT_PROPERTIES = "/META-INF/apionly/microcks/%4$s.properties";

                    /** This contract's identity, as the emitter wrote it. */
                    Properties CONTRACT = loadContractProperties();

                    /** The service name Microcks imports the contract under ({@code info.title}). */
                    String SERVICE_NAME = CONTRACT.getProperty("asyncapi.service.name");

                    /**
                     * The Microcks image this emitter was tested with. Read from the properties
                     * file, not compiled in, so a project can pin another one there without
                     * regenerating this interface.
                     */
                    String MICROCKS_IMAGE = CONTRACT.getProperty("microcks.image");

                    /** Where the ensemble {@link #startMicrocksEnsemble()} started is kept. */
                    AtomicReference<MicrocksContainersEnsemble> ENSEMBLE = new AtomicReference<>();

                    /** The Microcks service id {@link #startMicrocksEnsemble()} resolved. */
                    AtomicReference<String> SERVICE_ID = new AtomicReference<>();

                    /**
                     * Starts the Microcks ensemble, wired to this application's broker by
                     * {@link #wireBroker(MicrocksContainersEnsemble)}, and imports the contract
                     * {@link #contractFile()} names. Runs once for every test this interface
                     * declares.
                     *
                     * @throws IOException the contract could not be read
                     */
                    @BeforeAll
                    default void startMicrocksEnsemble() throws IOException {
                        MicrocksContainersEnsemble ensemble =
                                new MicrocksContainersEnsemble(Network.newNetwork(), MICROCKS_IMAGE)
                                        .withAsyncFeature();
                        wireBroker(ensemble);
                        ensemble.start();
                        try {
                            ensemble.getMicrocksContainer().importAsMainArtifact(contractFile().toFile());
                        } catch (MicrocksException e) {
                            throw new IllegalStateException(
                                    "Could not import " + contractFile() + " into Microcks.", e);
                        }
                        ENSEMBLE.set(ensemble);
                        SERVICE_ID.set(resolveServiceId(ensemble));
                    }

                    /** Stops the Microcks ensemble {@link #startMicrocksEnsemble()} started. */
                    @AfterAll
                    default void stopMicrocksEnsemble() {
                        MicrocksContainersEnsemble ensemble = ENSEMBLE.getAndSet(null);
                        if (ensemble != null) ensemble.stop();
                    }

                    /**
                     * Starts this application's message broker, and connects the Microcks
                     * ensemble to it, before {@code ensemble} is started. Attach the broker to
                     * {@code ensemble.getNetwork()} so the two can reach each other.
                     *
                     * @param ensemble the ensemble, not started yet
                     */
                    void wireBroker(MicrocksContainersEnsemble ensemble);

                    /**
                     * Where the fetched AsyncAPI document is, for Microcks to import. Typically a
                     * path the build wrote the contract to, such as
                     * {@code build/api-spec/<contract>/asyncapi.yaml}.
                     *
                     * @return the document's path
                     */
                    Path contractFile();

                    /**
                     * The endpoint Microcks tests against for a suffixed channel address, in the
                     * broker's own address form -- {@code "kafka://kafka:9092/" + suffixedChannel}
                     * for a Kafka broker reachable as {@code kafka} on
                     * {@code ensemble.getNetwork()}, for instance.
                     *
                     * @param suffixedChannel the channel address a test generated, with its
                     *                        isolation suffix
                     * @return the endpoint
                     */
                    String endpoint(String suffixedChannel);

                %5$s\
                    /** The service id {@link #startMicrocksEnsemble()} resolved. */
                    private static String serviceId() {
                        String id = SERVICE_ID.get();
                        if (id == null) {
                            throw new IllegalStateException("The Microcks ensemble has not started yet.");
                        }
                        return id;
                    }

                    /** The ensemble {@link #startMicrocksEnsemble()} started. */
                    private static MicrocksContainersEnsemble ensemble() {
                        MicrocksContainersEnsemble ensemble = ENSEMBLE.get();
                        if (ensemble == null) {
                            throw new IllegalStateException("The Microcks ensemble has not started yet.");
                        }
                        return ensemble;
                    }

                    /**
                     * The single Microcks service imported under {@link #SERVICE_NAME}, as
                     * {@code name:version}.
                     */
                    private static String resolveServiceId(MicrocksContainersEnsemble ensemble) {
                        List<ServiceRef> matches = ensemble.getMicrocksContainer().getServices().stream()
                                .filter(service -> SERVICE_NAME.equals(service.getName())).toList();
                        if (matches.size() != 1) {
                            throw new IllegalStateException("Expected exactly one Microcks service named '"
                                    + SERVICE_NAME + "', found " + matches.size() + ".");
                        }
                        return matches.get(0).getName() + ":" + matches.get(0).getVersion();
                    }

                    /** Every failed step of a test result's test cases, for a clear assertion. */
                    private static String diagnostics(TestResult result) {
                        StringBuilder out = new StringBuilder();
                        result.getTestCaseResults().forEach(testCase -> testCase.getTestStepResults().stream()
                                .filter(step -> !step.isSuccess())
                                .forEach(step -> out.append(testCase.getOperationName()).append(": ")
                                        .append(step.getMessage()).append('\\n')));
                        return out.toString();
                    }

                    /** {@link #CONTRACT}, read from {@link #CONTRACT_PROPERTIES}. */
                    private static Properties loadContractProperties() {
                        Properties properties = new Properties();
                        try (InputStream in =
                                     AsyncConformanceHarness.class.getResourceAsStream(CONTRACT_PROPERTIES)) {
                            if (in == null) {
                                throw new IllegalStateException(CONTRACT_PROPERTIES + " is not on the classpath.");
                            }
                            properties.load(in);
                        } catch (IOException e) {
                            throw new UncheckedIOException(e);
                        }
                        return properties;
                    }
                }
                """.formatted(pkg, imports, contract, contract, members);
    }

    /** The abstract hook that publishes one operation's message. */
    private static String hook(SendOperation operation) {
        return """
                    /**
                     * Publishes a message for operation {@code %1$s} on {@code suffixedChannel},
                     * through the application, exactly as production code would.
                     *
                     * @param suffixedChannel the channel address to publish on, with its
                     *                        isolation suffix
                     */
                    void %1$s(String suffixedChannel);

                """.formatted(operation.operationId());
    }

    /** The generated {@code @Test} that checks one operation against the contract. */
    private static String test(SendOperation operation) {
        return """
                    /**
                     * Publishes a message through {@link #%1$s(String)}, and checks it against
                     * operation {@code %1$s} of {@link %2$s}.
                     */
                    @Test
                    default void %1$s_conformsToContract() throws Exception {
                        String suffixedChannel = %2$s.CHANNEL_ADDRESS + "-" + UUID.randomUUID();
                        %1$s(suffixedChannel);
                        TestRequest request = new TestRequest.Builder()
                                .serviceId(serviceId())
                                .filteredOperations(List.of("SEND " + %2$s.OPERATION_ID))
                                .runnerType(TestRunnerType.ASYNC_API_SCHEMA)
                                .testEndpoint(endpoint(suffixedChannel))
                                .timeout(Duration.ofSeconds(10))
                                .build();
                        TestResult result = ensemble().getMicrocksContainer().testEndpointAsync(request)
                                .get(15, TimeUnit.SECONDS);
                        Assertions.assertTrue(result.isSuccess(), () -> diagnostics(result));
                    }

                """.formatted(operation.operationId(), operation.operationClass());
    }
}
