name: SEDR Library - Build
on:
  push:
    branches-ignore:
      - main
      - maintenance
    paths:
      - 'sedr-library/**'
      - '.github/workflows/sedr-library-build.yml'

jobs:
  Calculate-Version:
    uses: ./.github/workflows/semantic-version-calculate.yml
    with:
      fail_on_empty_version: false
      fail_on_existing_tag: false
      project_dir: sedr-library
    secrets:
      sem_rel_token_token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

  Determine-Release-Type:
    needs: Calculate-Version
    uses: ./.github/workflows/determine-release-type.yml

  Build-sedr-library:
    name: Build SEDR Library
    needs: Calculate-Version
    permissions:
      contents: read

    runs-on: ubuntu-latest

    env:
      GRADLE_PROPERTIES_FILE: ./sedr-library/gradle.properties
      GRADLE_VERSION_REGEX: version\s*=\s*[0-9]\\+\.[0-9]\\+\.[0-9]\\+[a-zA-Z0-9.-]*
      VERSION: ${{ needs.Calculate-Version.outputs.next_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6

      - name: Update version in Gradle property file
        if: ${{ env.VERSION != '' }}
        run: |
          echo "VERSION=${{ env.VERSION }}-PRERELEASE"
          echo ===== Before - ${{ env.GRADLE_PROPERTIES_FILE }} =====
          cat ${{ env.GRADLE_PROPERTIES_FILE }}
          sed -i "s/${{ env.GRADLE_VERSION_REGEX }}/version = ${{ env.VERSION }}-PRERELEASE/g" ${{ env.GRADLE_PROPERTIES_FILE }}
          echo ===== After - ${{ env.GRADLE_PROPERTIES_FILE }} =====
          cat ${{ env.GRADLE_PROPERTIES_FILE }}

      - name: Build SEDR Library
        run: |
          cd sedr-library
          chmod +x ./gradlew
          ./gradlew build
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.SEDR_AUTOMATION_TOKEN }}

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: sedr-library-build-reports
          path: sedr-library/build/reports/**

  Workflow-Summary:
    name: Workflow Summary
    needs: [Build-sedr-library, Determine-Release-Type]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Output build completion
        run: |
          echo "SEDR Library ${{ needs.Determine-Release-Type.outputs.release_type }} build workflow completed"
          echo "::notice title=Build Complete::SEDR Library ${{ needs.Determine-Release-Type.outputs.release_type }} build workflow completed"
